import { Effect, Modifier, ActionType, RangeType, DurationType } from './types'

export const ACTION_LABELS: Record<ActionType, string> = {
  padrao: 'Padrão',
  movimento: 'Movimento',
  livre: 'Livre',
  reacao: 'Reação',
  nenhuma: 'Nenhuma',
}

export const RANGE_LABELS: Record<RangeType, string> = {
  pessoal: 'Pessoal',
  perto: 'Perto',
  distancia: 'À Distância',
  percepcao: 'Percepção',
  graduacao: 'Graduação',
}

export const DURATION_LABELS: Record<DurationType, string> = {
  instantaneo: 'Instantâneo',
  concentracao: 'Concentração',
  sustentado: 'Sustentado',
  continuo: 'Contínuo',
  permanente: 'Permanente',
}

export const ACTION_DESCRIPTIONS: Record<ActionType, string> = {
  padrao: 'Usar o efeito exige uma ação padrão, que é a ação principal que você pode realizar em seu turno.',
  movimento: 'Usar o efeito exige uma ação de movimento, tipicamente usada para se mover ou para ações que consomem tempo semelhante.',
  livre: 'Usar ou ativar o efeito exige uma ação livre. Uma vez ativado, permanece assim até o próximo turno.',
  reacao: 'O efeito não exige ação e funciona automaticamente em resposta a um evento-gatilho específico.',
  nenhuma: 'O efeito não exige nenhuma ação e está sempre ativo.',
}

export const RANGE_DESCRIPTIONS: Record<RangeType, string> = {
  pessoal: 'O efeito funciona apenas em você, o usuário.',
  perto: 'O efeito pode visar qualquer coisa que você toque.',
  distancia: 'O efeito funciona à distância e exige um teste de ataque à distância.',
  percepcao: 'O efeito funciona em qualquer alvo que você possa perceber com um sentido acurado.',
  graduacao: 'O alcance ou área do efeito é determinado pela graduação do próprio efeito.',
}

export const DURATION_DESCRIPTIONS: Record<DurationType, string> = {
  instantaneo: 'O efeito ocorre e termina no mesmo turno, embora o seu resultado possa permanecer.',
  concentracao: 'Você pode manter o efeito usando uma ação padrão todo turno.',
  sustentado: 'Você pode manter o efeito usando uma ação livre todo turno.',
  continuo: 'O efeito dura o tempo que você quiser, sem exigir ação de manutenção.',
  permanente: 'O efeito está sempre ativo e não pode ser desativado.',
}

export const EFFECTS: Effect[] = [
  {
    id: 'aflicao',
    name: 'Aflição',
    baseCost: 1,
    description: 'Impõe condições debilitantes (como tonto, atordoado, ou incapacitado) no alvo após um ataque corpo-a-corpo bem-sucedido. O alvo pode resistir com Fortitude ou Vontade contra CD [graduação + 10].',
    action: 'padrao',
    range: 'perto',
    duration: 'instantaneo',
  },
  {
    id: 'alongamento',
    name: 'Alongamento',
    baseCost: 1,
    description: 'Permite esticar seu corpo ou membros, aumentando o seu alcance em combate e fornecendo bônus em testes de agarrar.',
    action: 'livre',
    range: 'pessoal',
    duration: 'sustentado',
  },
  {
    id: 'ambiente',
    name: 'Ambiente',
    baseCost: 1,
    description: 'Permite alterar o ambiente ao seu redor (calor, frio, visibilidade ou impedimento de movimento) em uma área determinada pela graduação do efeito.',
    action: 'padrao',
    range: 'graduacao',
    duration: 'sustentado',
  },
  {
    id: 'camuflagem',
    name: 'Camuflagem',
    baseCost: 2,
    description: 'Concede camuflagem total contra um sentido específico ou tipo de sentido, tornando-o mais difícil de ser percebido ou mirado.',
    action: 'livre',
    range: 'pessoal',
    duration: 'sustentado',
  },
  {
    id: 'caracteristica',
    name: 'Característica',
    baseCost: 1,
    description: 'Concede uma característica ou benefício menor que tem impacto no jogo, funcionando como uma habilidade menor.',
    action: 'nenhuma',
    range: 'pessoal',
    duration: 'permanente',
  },
  {
    id: 'caracteristica-aumentada',
    name: 'Característica Aumentada',
    baseCost: 1,
    description: 'Aumenta temporariamente uma característica (habilidade, defesa, etc.) na quantidade de graduações do efeito, custando o mesmo que a característica básica.',
    action: 'livre',
    range: 'pessoal',
    duration: 'sustentado',
  },
  {
    id: 'compreender',
    name: 'Compreender',
    baseCost: 2,
    description: 'Permite compreender ou falar diferentes formas de comunicação, como línguas, comunicação animal, ou espíritos, dependendo das graduações.',
    action: 'nenhuma',
    range: 'pessoal',
    duration: 'permanente',
  },
  {
    id: 'comunicacao',
    name: 'Comunicação',
    baseCost: 4,
    description: 'Permite comunicar-se à distância usando um meio que não a voz normal (mental, rádio, tátil, etc.). O alcance é determinado pela graduação do efeito.',
    action: 'livre',
    range: 'graduacao',
    duration: 'sustentado',
  },
  {
    id: 'controle-sorte',
    name: 'Controle da Sorte',
    baseCost: 3,
    description: 'Permite gastar pontos heroicos ou usos da vantagem Sorte para afetar as rolagens e a sorte de outros personagens.',
    action: 'reacao',
    range: 'percepcao',
    duration: 'instantaneo',
  },
  {
    id: 'crescimento',
    name: 'Crescimento',
    baseCost: 2,
    description: 'Aumenta temporariamente o seu tamanho, concedendo Força e Vigor aumentados, mas reduzindo a agilidade e a furtividade.',
    action: 'livre',
    range: 'pessoal',
    duration: 'sustentado',
  },
  {
    id: 'criar',
    name: 'Criar',
    baseCost: 2,
    description: 'Permite conjurar objetos sólidos e estacionários de um meio específico (rocha, gelo, energia, etc.), com volume e Resistência baseados na graduação.',
    action: 'padrao',
    range: 'distancia',
    duration: 'sustentado',
  },
  {
    id: 'cura',
    name: 'Cura',
    baseCost: 2,
    description: 'Permite remover condições de dano e estabilizar alvos moribundos (CD 10). Também pode conceder bônus para resistir a doenças e venenos.',
    action: 'padrao',
    range: 'perto',
    duration: 'instantaneo',
  },
  {
    id: 'dano',
    name: 'Dano',
    baseCost: 1,
    description: 'Causa dano físico a um alvo em combate corpo-a-corpo, forçando um teste de Resistência. A falha resulta em penalidades cumulativas, tontura, abatimento ou incapacitação.',
    action: 'padrao',
    range: 'perto',
    duration: 'instantaneo',
  },
  {
    id: 'deflexao',
    name: 'Deflexão',
    baseCost: 1,
    description: 'Permite defender ativamente outros personagens contra ataques à distância, substituindo a defesa normal do alvo.',
    action: 'padrao',
    range: 'distancia',
    duration: 'instantaneo',
  },
  {
    id: 'encolhimento',
    name: 'Encolhimento',
    baseCost: 2,
    description: 'Permite diminuir temporariamente o seu tamanho, aumentando a furtividade e as defesas ativas, mas reduzindo a Força e a velocidade.',
    action: 'livre',
    range: 'pessoal',
    duration: 'sustentado',
  },
  {
    id: 'enfraquecer',
    name: 'Enfraquecer',
    baseCost: 1,
    description: 'Reduz temporariamente uma característica específica (habilidade, perícia, poder) do alvo. A perda de pontos é cumulativa e reversível ao longo do tempo.',
    action: 'padrao',
    range: 'perto',
    duration: 'instantaneo',
  },
  {
    id: 'escavacao',
    name: 'Escavação',
    baseCost: 1,
    description: 'Permite mover-se através do solo (terra e areia) com uma velocidade reduzida, que pode ser ainda mais reduzida ao escavar rocha.',
    action: 'livre',
    range: 'pessoal',
    duration: 'sustentado',
  },
  {
    id: 'ilusao',
    name: 'Ilusão',
    baseCost: 1,
    description: 'Cria impressões falsas controlando os sentidos dos outros, que podem variar de sons e imagens a percepções mentais.',
    action: 'padrao',
    range: 'percepcao',
    duration: 'sustentado',
  },
  {
    id: 'imortalidade',
    name: 'Imortalidade',
    baseCost: 2,
    description: 'Permite retornar à vida após a morte, com o tempo de recuperação diminuindo com graduações mais altas.',
    action: 'nenhuma',
    range: 'pessoal',
    duration: 'permanente',
  },
  {
    id: 'imunidade',
    name: 'Imunidade',
    baseCost: 1,
    description: 'Concede imunidade a efeitos específicos, permitindo que o personagem ignore testes de salvamento contra eles. O custo varia de 1 a 80 pontos, dependendo da abrangência do efeito.',
    action: 'nenhuma',
    range: 'pessoal',
    duration: 'permanente',
  },
  {
    id: 'intangibilidade',
    name: 'Intangibilidade',
    baseCost: 5,
    description: 'Permite assumir uma forma menos sólida (fluida, gasosa, energética ou fantasmagórica), ganhando imunidade a dano físico e a capacidade de atravessar objetos sólidos.',
    action: 'livre',
    range: 'pessoal',
    duration: 'sustentado',
  },
  {
    id: 'invocar',
    name: 'Invocar',
    baseCost: 2,
    description: 'Permite chamar um capanga (personagem criado com 15 pontos de poder por graduação) para ajudá-lo. O capanga age sob suas ordens, mas geralmente está sujeito à condição tonto.',
    action: 'padrao',
    range: 'perto',
    duration: 'sustentado',
  },
  {
    id: 'leitura-mental',
    name: 'Leitura Mental',
    baseCost: 2,
    description: 'Permite ler a mente do alvo. O grau de contato (pensamentos superficiais, memórias, subconsciente) é determinado pelo grau de sucesso num teste oposto contra Vontade.',
    action: 'padrao',
    range: 'percepcao',
    duration: 'sustentado',
  },
  {
    id: 'membros-extras',
    name: 'Membros Extras',
    baseCost: 1,
    description: 'Concede membros manipuladores adicionais, o que pode fornecer bônus em testes de agarrar ou permitir que você segure mais objetos.',
    action: 'nenhuma',
    range: 'pessoal',
    duration: 'permanente',
  },
  {
    id: 'morfar',
    name: 'Morfar',
    baseCost: 5,
    description: 'Permite alterar a aparência (mas não as características) para se disfarçar em outra forma. Garante um bônus de +20 em testes de Enganação para disfarce.',
    action: 'livre',
    range: 'pessoal',
    duration: 'sustentado',
  },
  {
    id: 'mover-objeto',
    name: 'Mover Objeto',
    baseCost: 2,
    description: 'Permite mover objetos sem contato físico, usando a graduação do efeito como Força efetiva para erguer e mover peso.',
    action: 'padrao',
    range: 'distancia',
    duration: 'sustentado',
  },
  {
    id: 'movimento',
    name: 'Movimento',
    baseCost: 2,
    description: 'Concede formas especiais de movimento, como Andar na Água, Balançar-se, Escalar Paredes, Permear, Viagem Dimensional, ou Viagem Temporal. Cada opção custa 2 pontos por graduação.',
    action: 'livre',
    range: 'pessoal',
    duration: 'sustentado',
  },
  {
    id: 'natacao',
    name: 'Natação',
    baseCost: 1,
    description: 'Concede velocidade aquática (graduação do efeito - 2).',
    action: 'livre',
    range: 'pessoal',
    duration: 'sustentado',
  },
  {
    id: 'nulificar',
    name: 'Nulificar',
    baseCost: 1,
    description: 'Permite contra-atacar ou desligar os efeitos de um poder com um descritor específico (magia, eletricidade, etc.). Exige um teste oposto bem-sucedido contra a graduação do efeito ou a Vontade do usuário.',
    action: 'padrao',
    range: 'distancia',
    duration: 'instantaneo',
  },
  {
    id: 'protecao',
    name: 'Proteção',
    baseCost: 1,
    description: 'Fornece um bônus de +1 à sua defesa Resistência por graduação.',
    action: 'nenhuma',
    range: 'pessoal',
    duration: 'permanente',
  },
  {
    id: 'rapidez',
    name: 'Rapidez',
    baseCost: 1,
    description: 'Permite realizar tarefas de rotina (que podem ser feitas com testes de rotina) muito mais rápido, reduzindo o tempo necessário.',
    action: 'livre',
    range: 'pessoal',
    duration: 'sustentado',
  },
  {
    id: 'regeneracao',
    name: 'Regeneração',
    baseCost: 1,
    description: 'Permite recuperar-se rapidamente de dano, removendo penalidades de Resistência ou outras condições de dano ao longo do tempo.',
    action: 'nenhuma',
    range: 'pessoal',
    duration: 'permanente',
  },
  {
    id: 'salto',
    name: 'Salto',
    baseCost: 1,
    description: 'Permite dar saltos longos (a distância coberta é determinada pela graduação do efeito) sem sofrer dano na aterrissagem.',
    action: 'livre',
    range: 'pessoal',
    duration: 'instantaneo',
  },
  {
    id: 'sentidos',
    name: 'Sentidos',
    baseCost: 1,
    description: 'Melhora ou adiciona sentidos (visão no escuro, sentidos acurados, ultra-audição, etc.). O custo varia dependendo do tipo e abrangência do sentido.',
    action: 'nenhuma',
    range: 'pessoal',
    duration: 'permanente',
  },
  {
    id: 'sentido-remoto',
    name: 'Sentido Remoto',
    baseCost: 1,
    description: 'Permite deslocar um ou mais sentidos para longe, percebendo o ambiente como se estivesse no local remoto.',
    action: 'livre',
    range: 'graduacao',
    duration: 'sustentado',
  },
  {
    id: 'teleporte',
    name: 'Teleporte',
    baseCost: 2,
    description: 'Permite mover-se instantaneamente para outro local dentro do alcance da graduação do efeito, sem atravessar a distância intermediária.',
    action: 'movimento',
    range: 'graduacao',
    duration: 'instantaneo',
  },
  {
    id: 'transformacao',
    name: 'Transformação',
    baseCost: 2,
    description: 'Permite alterar a forma ou composição material de objetos inanimados (como metal em água), que revertem ao normal quando o efeito não é mantido.',
    action: 'padrao',
    range: 'perto',
    duration: 'sustentado',
  },
  {
    id: 'variavel',
    name: 'Variável',
    baseCost: 7,
    description: 'Concede um conjunto de (graduação x 5) pontos de poder que podem ser alocados para diferentes efeitos de um tipo e descritor apropriados. Permite grande flexibilidade, mas requer uma ação para reconfigurar.',
    action: 'padrao',
    range: 'pessoal',
    duration: 'sustentado',
  },
  {
    id: 'velocidade',
    name: 'Velocidade',
    baseCost: 1,
    description: 'Permite mover-se mais rápido que o normal, aumentando sua velocidade terrestre. O efeito também melhora outras formas de movimento baseadas na velocidade terrestre.',
    action: 'livre',
    range: 'pessoal',
    duration: 'sustentado',
  },
  {
    id: 'voo',
    name: 'Voo',
    baseCost: 2,
    description: 'Permite voar ou flutuar, concedendo uma graduação de velocidade de voo igual à graduação do efeito.',
    action: 'livre',
    range: 'pessoal',
    duration: 'sustentado',
  },
]

export const COMMON_EXTRAS: Modifier[] = [
  { id: 'acurado', name: 'Acurado', type: 'extra', costPerRank: 1, isFlat: true, description: 'Adiciona +2 por graduação nos testes de ataque feitos com o efeito.' },
  { id: 'afeta-corporeo', name: 'Afeta Corpóreo', type: 'extra', costPerRank: 1, isFlat: true, description: 'Permite que um ser intangível use o efeito no mundo corpóreo.' },
  { id: 'afeta-intangivel', name: 'Afeta Intangível', type: 'extra', costPerRank: 1, isFlat: true, description: 'Faz com que o efeito funcione contra alvos intangíveis.' },
  { id: 'afeta-objetos', name: 'Afeta Objetos', type: 'extra', costPerRank: 1, description: 'Permite que efeitos normalmente resistidos por Fortitude funcionem em objetos não vivos.' },
  { id: 'afeta-outros', name: 'Afeta Outros', type: 'extra', costPerRank: 1, description: 'Permite estender um efeito de alcance pessoal a outros.' },
  { id: 'alcance', name: 'Alcance', type: 'extra', costPerRank: 1, isFlat: true, description: 'Aumenta o alcance de um efeito de perto em 1,5 metros por graduação.' },
  { id: 'alcance-estendido', name: 'Alcance Estendido', type: 'extra', costPerRank: 1, isFlat: true, description: 'Dobra todas as categorias de alcance de um efeito à distância.' },
  { id: 'area', name: 'Área', type: 'extra', costPerRank: 1, description: 'Permite que o efeito afete uma área em vez de um único alvo.' },
  { id: 'ataque', name: 'Ataque', type: 'extra', costPerRank: 0, description: 'Transforma um efeito de alcance pessoal em um efeito de ataque de alcance perto.' },
  { id: 'aumentar-massa', name: 'Aumentar Massa', type: 'extra', costPerRank: 1, isFlat: true, description: 'Aumenta a graduação de massa que o efeito pode carregar.' },
  { id: 'caracteristica', name: 'Característica', type: 'extra', costPerRank: 1, isFlat: true, description: 'Adiciona uma habilidade ou benefício menor ao efeito básico.' },
  { id: 'contagioso', name: 'Contagioso', type: 'extra', costPerRank: 1, description: 'O efeito funciona em qualquer um que entre em contato com o alvo original.' },
  { id: 'descritor-variavel', name: 'Descritor Variável', type: 'extra', costPerRank: 1, isFlat: true, description: 'Permite mudar o descritor de um efeito como uma ação livre.' },
  { id: 'dimensional', name: 'Dimensional', type: 'extra', costPerRank: 1, isFlat: true, description: 'Permite que o efeito funcione em alvos em outras dimensões.' },
  { id: 'distancia-aumentada', name: 'Distância Aumentada', type: 'extra', costPerRank: 1, description: 'Melhora o alcance de um efeito (ex: de perto para à distância).' },
  { id: 'dividido', name: 'Dividido', type: 'extra', costPerRank: 1, isFlat: true, description: 'Permite que o efeito seja dividido entre dois ou mais alvos.' },
  { id: 'duracao-aumentada', name: 'Duração Aumentada', type: 'extra', costPerRank: 1, description: 'Aumenta a duração de um efeito (ex: de instantâneo para concentração).' },
  { id: 'efeito-alternativo', name: 'Efeito Alternativo', type: 'extra', costPerRank: 1, isFlat: true, description: 'Permite trocar um efeito por outro (arranjo).' },
  { id: 'efeito-secundario', name: 'Efeito Secundário', type: 'extra', costPerRank: 1, description: 'Um efeito instantâneo atinge o alvo uma segunda vez na rodada seguinte.' },
  { id: 'engatilhado', name: 'Engatilhado', type: 'extra', costPerRank: 1, isFlat: true, description: 'Permite que um efeito instantâneo seja ativado automaticamente sob circunstâncias específicas.' },
  { id: 'impenetravel', name: 'Impenetrável', type: 'extra', costPerRank: 1, description: 'Torna uma defesa altamente resistente a efeitos mais fracos.' },
  { id: 'inato', name: 'Inato', type: 'extra', costPerRank: 1, isFlat: true, description: 'O efeito é parte inata de sua natureza e não pode ser Nulificado.' },
  { id: 'incuravel', name: 'Incurável', type: 'extra', costPerRank: 1, isFlat: true, description: 'O dano ou condição causada pelo efeito não podem ser curados normalmente.' },
  { id: 'indireto', name: 'Indireto', type: 'extra', costPerRank: 1, isFlat: true, description: 'Permite que o efeito se origine de um ponto que não seja o usuário.' },
  { id: 'ligado', name: 'Ligado', type: 'extra', costPerRank: 0, isFlat: true, description: 'Combina dois ou mais efeitos para que funcionem simultaneamente.' },
  { id: 'multiataque', name: 'Multiataque', type: 'extra', costPerRank: 1, description: 'Permite atingir múltiplos alvos ou um único alvo múltiplas vezes.' },
  { id: 'penetrante', name: 'Penetrante', type: 'extra', costPerRank: 1, isFlat: true, description: 'O efeito ignora Resistência Impenetrável.' },
  { id: 'preciso', name: 'Preciso', type: 'extra', costPerRank: 1, isFlat: true, description: 'Permite realizar tarefas que exijam delicadeza e controle fino.' },
  { id: 'reacao', name: 'Reação', type: 'extra', costPerRank: 1, description: 'Altera a ação exigida para o efeito funcionar como uma reação.' },
  { id: 'resistencia-alternativa', name: 'Resistência Alternativa', type: 'extra', costPerRank: 1, description: 'Altera o teste de salvamento do efeito.' },
  { id: 'reversivel', name: 'Reversível', type: 'extra', costPerRank: 1, isFlat: true, description: 'Permite remover condições ou danos causados pelo efeito à vontade.' },
  { id: 'ricochetear', name: 'Ricochetear', type: 'extra', costPerRank: 1, isFlat: true, description: 'Permite que o ataque ricocheteie em superfícies para mudar sua direção.' },
  { id: 'seletivo', name: 'Seletivo', type: 'extra', costPerRank: 1, description: 'Permite escolher quem é ou não afetado por um efeito.' },
  { id: 'sonifero', name: 'Sonífero', type: 'extra', costPerRank: 0, description: 'Deixa o alvo adormecido em vez de incapacitado.' },
  { id: 'sustentado', name: 'Sustentado', type: 'extra', costPerRank: 0, description: 'Altera um efeito de duração permanente para sustentada.' },
  { id: 'sutil', name: 'Sutil', type: 'extra', costPerRank: 1, isFlat: true, description: 'Torna o efeito menos perceptível ou indetectável.' },
  { id: 'teleguiado', name: 'Teleguiado', type: 'extra', costPerRank: 1, isFlat: true, description: 'Concede uma oportunidade adicional de acertar um ataque à distância.' },
  { id: 'traicoeiro', name: 'Traiçoeiro', type: 'extra', costPerRank: 1, isFlat: true, description: 'Torna o resultado do efeito mais difícil de detectar.' },
]

export const COMMON_FLAWS: Modifier[] = [
  { id: 'acao-aumentada', name: 'Ação Aumentada', type: 'falha', costPerRank: -1, description: 'Aumenta a ação exigida para usar o efeito.' },
  { id: 'alcance-diminuido', name: 'Alcance Diminuído', type: 'falha', costPerRank: -1, isFlat: true, description: 'Reduz os multiplicadores de alcance para um efeito à distância.' },
  { id: 'alcance-reduzido', name: 'Alcance Reduzido', type: 'falha', costPerRank: -1, description: 'Diminui o alcance de um efeito em um passo.' },
  { id: 'ativacao', name: 'Ativação', type: 'falha', costPerRank: -1, isFlat: true, description: 'O poder exige uma ação para ser preparado antes do uso.' },
  { id: 'baseado-em-agarrar', name: 'Baseado em Agarrar', type: 'falha', costPerRank: -1, description: 'O efeito só pode ser usado após um teste de agarrar bem-sucedido.' },
  { id: 'cansativo', name: 'Cansativo', type: 'falha', costPerRank: -1, description: 'O uso do efeito causa um nível de fadiga ao personagem.' },
  { id: 'concentracao', name: 'Concentração', type: 'falha', costPerRank: -1, description: 'Exige uma ação padrão por turno para manter o efeito.' },
  { id: 'dependente-de-sentido', name: 'Dependente de Sentido', type: 'falha', costPerRank: -1, description: 'O alvo deve ser capaz de perceber o efeito para que ele funcione.' },
  { id: 'dissipacao', name: 'Dissipação', type: 'falha', costPerRank: -1, description: 'O efeito perde eficiência cada vez que é usado.' },
  { id: 'distracao', name: 'Distração', type: 'falha', costPerRank: -1, description: 'O personagem fica vulnerável enquanto usa o efeito.' },
  { id: 'efeito-colateral', name: 'Efeito Colateral', type: 'falha', costPerRank: -1, description: 'Falhar ao usar o efeito causa um problema ao personagem.' },
  { id: 'exige-teste', name: 'Exige Teste', type: 'falha', costPerRank: -1, isFlat: true, description: 'O personagem deve ser bem-sucedido em um teste para que o efeito funcione.' },
  { id: 'inconstante', name: 'Inconstante', type: 'falha', costPerRank: -1, description: 'O efeito funciona apenas metade do tempo ou usos limitados.' },
  { id: 'incontrolavel', name: 'Incontrolável', type: 'falha', costPerRank: -1, description: 'O personagem não tem controle sobre o efeito.' },
  { id: 'impreciso', name: 'Impreciso', type: 'falha', costPerRank: -1, isFlat: true, description: 'Impõe uma penalidade de -2 nos testes de ataque com o efeito.' },
  { id: 'limitado', name: 'Limitado', type: 'falha', costPerRank: -1, description: 'O efeito funciona apenas em certas situações.' },
  { id: 'peculiaridade', name: 'Peculiaridade', type: 'falha', costPerRank: -1, isFlat: true, description: 'Um incômodo menor ligado ao efeito.' },
  { id: 'perceptivel', name: 'Perceptível', type: 'falha', costPerRank: -1, isFlat: true, description: 'Um efeito contínuo ou permanente é perceptível.' },
  { id: 'permanente', name: 'Permanente', type: 'falha', costPerRank: -1, description: 'O efeito está sempre ativo e não pode ser desligado.' },
  { id: 'removivel', name: 'Removível', type: 'falha', costPerRank: -1, isFlat: true, description: 'O poder reside em um dispositivo externo que pode ser tirado.' },
  { id: 'resistivel', name: 'Resistível', type: 'falha', costPerRank: -1, description: 'Concede um teste de salvamento a um efeito que normalmente não teria.' },
  { id: 'retroalimentacao', name: 'Retroalimentação', type: 'falha', costPerRank: -1, description: 'O usuário sofre dano quando a manifestação física de seu efeito sofre dano.' },
]

export const COMMON_DESCRIPTORS = [
  'Fogo',
  'Gelo',
  'Eletricidade',
  'Luz',
  'Trevas',
  'Força',
  'Psíquico',
  'Mágico',
  'Tecnológico',
  'Cósmico',
  'Divino',
  'Demoníaco',
  'Radioativo',
  'Sônico',
  'Cinético',
  'Gravitacional',
  'Dimensional',
  'Temporal',
  'Biológico',
  'Químico',
]

export const POWER_TIPS = {
  effect: 'Os Efeitos são os blocos de construção que definem a função do poder. Cada efeito tem um custo base por graduação.',
  rank: 'A Graduação determina a potência do efeito. Quanto maior, mais poderoso e mais caro.',
  modifiers: 'Extras aumentam o custo e a eficácia. Falhas diminuem o custo mas adicionam limitações.',
  descriptors: 'Descritores definem como o poder se manifesta (Fogo, Mágico, Tecnológico) e suas interações.',
  action: 'O tempo necessário para ativar o efeito: Padrão, Movimento, Livre, Reação ou Nenhuma.',
  range: 'A distância máxima do efeito: Pessoal, Perto, À Distância, Percepção ou Graduação.',
  duration: 'Por quanto tempo o efeito persiste: Instantâneo, Concentração, Sustentado, Contínuo ou Permanente.',
  cost: 'Custo = ((base + extras - falhas) × graduação) + fixos. Mínimo de 1 PP por 5 graduações.',
}
