export const AMBIENTE_SUBS = [
  {
    id: "calor-frio",
    label: "Calor ou Frio",
    maxRank: 5,
    tip: "O efeito gera calor/frio moderado ou intenso, aumentando intensidade e área com mais graduações.",
  },
  {
    id: "impedir-movimento",
    label: "Impedir Movimento",
    maxRank: 5,
    tip: "A velocidade na área é reduzida significativamente por cada graduação.",
  },
  {
    id: "luz",
    label: "Luz",
    maxRank: 2,
    tip: "Gera luz suficiente para reduzir ou eliminar camuflagem na área.",
  },
  {
    id: "visibilidade",
    label: "Visibilidade",
    maxRank: 5,
    tip: "Impõe uma penalidade em testes de Percepção na área por graduação.",
  },
];

export const COMPREENDER_SUBS = [
  {
    id: "animais",
    label: "Animais",
    maxRank: 2,
    tip: "1 Graduação: Você pode entender animais.\n2 Graduações: Você pode entender e falar com animais.",
  },
  {
    id: "espiritos",
    label: "Espíritos",
    maxRank: 2,
    tip: "1 Graduação: Você pode entender espíritos.\n2 Graduações: Você pode entender e falar com espíritos.",
  },
  {
    id: "idiomas",
    label: "Idiomas",
    maxRank: 4,
    tip: "1 Graduação: Entende um idioma.\n2 Graduações: Fala um idioma.\n3 Graduações: Lê um idioma.\n4 Graduações: Entende todos, fala todos, lê todos.",
  },
  {
    id: "maquinas",
    label: "Máquinas",
    maxRank: 2,
    tip: "1 Graduação: Você pode entender máquinas.\n2 Graduações: Você pode entender e falar com máquinas.",
  },
  {
    id: "objetos",
    label: "Objetos",
    maxRank: 2,
    tip: "1 Graduação: Você pode entender objetos.\n2 Graduações: Você pode entender e falar com objetos.",
  },
  {
    id: "plantas",
    label: "Plantas",
    maxRank: 2,
    tip: "1 Graduação: Você pode entender plantas.\n2 Graduações: Você pode entender e falar com plantas.",
  },
];

export const CARACTERISTICA_CATEGORIES = [
  {
    id: "habilidades",
    label: "Habilidades",
    cost: 2,
    items: [
      { id: "FOR", label: "Força" },
      { id: "VIG", label: "Vigor" },
      { id: "AGI", label: "Agilidade" },
      { id: "DES", label: "Destreza" },
      { id: "LUT", label: "Luta" },
      { id: "INT", label: "Intelecto" },
      { id: "PRO", label: "Prontidão" },
      { id: "PRE", label: "Presença" },
    ],
  },
  {
    id: "defesas",
    label: "Defesas",
    cost: 1,
    items: [
      { id: "ESQUIVA", label: "Esquiva" },
      { id: "APARAR", label: "Aparar" },
      { id: "FORTITUDE", label: "Fortitude" },
      { id: "VONTADE", label: "Vontade" },
      { id: "INICIATIVA", label: "Iniciativa" },
    ],
  },
  {
    id: "pericias",
    label: "Perícias",
    cost: 0.5,
    items: [
      { id: "ACRO", label: "Acrobacia" },
      { id: "ATLETISMO", label: "Atletismo" },
      { id: "COMBATE_DISTANCIA", label: "Combate à Distância" },
      { id: "COMBATE_CORPO_A_CORPO", label: "Combate Corpo-a-Corpo" },
      { id: "ENGANACAO", label: "Enganação" },
      { id: "ESPECIALIDADE", label: "Especialidade" },
      { id: "FURTIVIDADE", label: "Furtividade" },
      { id: "INTIMIDACAO", label: "Intimidação" },
      { id: "INTUICAO", label: "Intuição" },
      { id: "INVESTIGACAO", label: "Investigação" },
      { id: "PERCEPCAO", label: "Percepção" },
      { id: "PERSUASAO", label: "Persuasão" },
      { id: "PRESTIDIGITACAO", label: "Prestidigitação" },
      { id: "TECNOLOGIA", label: "Tecnologia" },
      { id: "TRATAMENTO", label: "Tratamento" },
      { id: "VEICULOS", label: "Veículos" },
    ],
  },
  {
    id: "vantagens",
    label: "Vantagens",
    cost: 1,
    items: [
      { id: "combate", label: "Vantagens de Combate" },
      { id: "pericia", label: "Vantagens de Perícia" },
      { id: "sorte", label: "Vantagens de Sorte" },
      { id: "gerais", label: "Vantagens Gerais" },
    ],
  },
];

export const MOVIMENTO_SUBS = [
  {
    id: "adaptacao",
    label: "Adaptação ao Ambiente",
    maxRank: 1,
    tip: "Escolha um ambiente (subaquático, gravidade zero, etc.). Você não sofre penalidades de movimento associadas.",
  },
  {
    id: "andar-agua",
    label: "Andar na Água",
    maxRank: 2,
    tip: "1 Graduação: Mover-se sobre líquidos sem afundar.\n2 Graduações: Pode ficar caído na superfície sem afundar.",
  },
  {
    id: "balancar",
    label: "Balançar-se",
    maxRank: 1,
    tip: "Mover-se pelo ar à sua velocidade terrestre normal usando uma linha (teias, cordas, cipós).",
  },
  {
    id: "deslizar",
    label: "Deslizar",
    maxRank: 1,
    tip: "Mover-se enquanto caído à velocidade normal e sem penalidade para atacar.",
  },
  {
    id: "escalar",
    label: "Escalar Paredes",
    maxRank: 2,
    tip: "1 Graduação: Velocidade terrestre -1 e vulnerável.\n2 Graduações: Velocidade total e não fica vulnerável.",
  },
  {
    id: "estabilidade",
    label: "Estabilidade",
    maxRank: 3,
    tip: "Reduza penalidades por obstáculos em 1 por graduação.",
  },
  {
    id: "dimensional",
    label: "Movimento Dimensional",
    maxRank: 3,
    tip: "1 Graduação: Uma outra dimensão.\n2 Graduações: Grupo de dimensões relacionadas.\n3 Graduações: Qualquer dimensão.",
  },
  {
    id: "permear",
    label: "Permear",
    maxRank: 3,
    tip: "1 Graduação: Velocidade -2.\n2 Graduações: Velocidade -1.\n3 Graduações: Velocidade normal.",
  },
  {
    id: "queda-segura",
    label: "Queda Segura",
    maxRank: 1,
    tip: "Cair de qualquer distância sem se ferir (exige capacidade de agir).",
  },
  {
    id: "sem-rastros",
    label: "Sem Rastros",
    maxRank: 3,
    tip: "1 Graduação: Imune a rastreio visual e sentido sísmico.\nCada graduação adicional cobre outro tipo de sentido.",
  },
  {
    id: "espacial",
    label: "Viagem Espacial",
    maxRank: 3,
    tip: "1 Graduação: Outros planetas.\n2 Graduações: Outros sistemas estelares.\n3 Graduações: Sistemas distantes ou galáxias.",
  },
  {
    id: "temporal",
    label: "Viagem Temporal",
    maxRank: 3,
    tip: "1 Graduação: Entre o presente e ponto fixo.\n2 Graduações: Qualquer ponto no passado ou futuro (um deles).\n3 Graduações: Qualquer ponto no tempo.",
  },
];

export const SENTIDOS_SUBS = [
  {
    id: "acurado",
    label: "Acurado",
    maxRank: 4,
    tip: "Acurado (2 graduações para um sentido, 4 para um tipo): Aponta a localização exata, permitindo mirar em combate.",
  },
  {
    id: "a-distancia",
    label: "À Distância",
    maxRank: 1,
    tip: "À Distância (1 graduação): Permite usar um sentido que normalmente não tem alcance para testes de Percepção à distância.",
  },
  {
    id: "agucado",
    label: "Aguçado",
    maxRank: 2,
    tip: "Aguçado (1 graduação para um sentido, 2 para um tipo): Permite distinguir e identificar diferentes alvos com detalhes finos.",
  },
  {
    id: "analitico",
    label: "Analítico",
    maxRank: 2,
    tip: "Analítico (1 graduação para um sentido, 2 para um tipo): Percebe detalhes específicos (composição química, massa, frequência), exige um sentido aguçado.",
  },
  {
    id: "contra-ataca-camuflagem",
    label: "Contra-Ataca Camuflagem",
    maxRank: 5,
    tip: "Contra-Ataca Camuflagem (2 graduações: um descritor específico; 5 graduações: todos os descritores): Ignora efeitos de Camuflagem.",
  },
  {
    id: "contra-ataca-ilusao",
    label: "Contra-Ataca Ilusão",
    maxRank: 2,
    tip: "Contra-Ataca Ilusão (2 graduações): O tipo de sentido ignora o efeito Ilusão, sendo automaticamente bem-sucedido no salvamento.",
  },
  {
    id: "deteccao",
    label: "Detecção",
    maxRank: 2,
    tip: "Detecção (1 graduação: perto; 2 graduações: à distância): Sente um item ou efeito específico através do toque.",
  },
  {
    id: "elo-comunicacao",
    label: "Elo de Comunicação",
    maxRank: 1,
    tip: "Elo de Comunicação (1 graduação): Elo com um indivíduo específico para comunicação a qualquer distância.",
  },
  {
    id: "estendido",
    label: "Estendido",
    maxRank: 10,
    tip: "Estendido (1 graduação): Aumenta o alcance de percepção em um fator de 10 por graduação.",
  },
  {
    id: "infravisao",
    label: "Infravisão",
    maxRank: 1,
    tip: "Infravisão (1 graduação): Vê o espectro infravermelho (padrões de calor) e rastreia trilhas de calor.",
  },
  {
    id: "penetra-camuflagem",
    label: "Penetra Camuflagem",
    maxRank: 4,
    tip: "Penetra Camuflagem (4 graduações): Enxerga através de obstáculos físicos (objetos opacos, isolamento acústico, etc.).",
  },
  {
    id: "percepcao",
    label: "Percepção",
    maxRank: 2,
    tip: "Percepção (1 graduação: perto; 2 graduações: à distância): Sente o uso de um descritor específico (Ex: Percepção Cósmica, Mental).",
  },
  {
    id: "poscognicao",
    label: "Póscognição",
    maxRank: 4,
    tip: "Póscognição (4 graduações; 2 se limitada): Percebe eventos passados. Exige concentração; sentidos normais não funcionam.",
  },
  {
    id: "precognicao",
    label: "Precognição",
    maxRank: 4,
    tip: "Precognição (4 graduações): Percebe futuros possíveis. Exige concentração; sentidos normais não funcionam.",
  },
  {
    id: "radio",
    label: "Rádio",
    maxRank: 1,
    tip: "Rádio (1 graduação): Sente frequências de rádio, TV, celular. É à distância, radial e acurado por padrão.",
  },
  {
    id: "radial",
    label: "Radial",
    maxRank: 2,
    tip: "Radial (1 graduação para um sentido, 2 para um tipo): Percepção em 360 graus ao redor do personagem.",
  },
  {
    id: "rapido",
    label: "Rápido",
    maxRank: 10,
    tip: "Rápido (1 graduação): Aumenta a velocidade de percepção em um fator de 10 por graduação.",
  },
  {
    id: "rastrear",
    label: "Rastrear",
    maxRank: 2,
    tip: "Rastrear (1 graduação: velocidade -1; 2 graduações: velocidade normal): Segue trilhas e rastros com um sentido.",
  },
  {
    id: "direcao",
    label: "Sentido de Direção",
    maxRank: 1,
    tip: "Sentido de Direção (1 graduação): Sabe sempre o norte e pode refazer seus passos.",
  },
  {
    id: "distancia",
    label: "Sentido de Distância",
    maxRank: 1,
    tip: "Sentido de Distância (1 graduação): Julga distâncias automaticamente e com precisão.",
  },
  {
    id: "perigo",
    label: "Sentido de Perigo",
    maxRank: 1,
    tip: "Sentido de Perigo (1 graduação): Teste de Percepção (CD 10) para não ficar surpreendido em combate.",
  },
  {
    id: "tempo",
    label: "Sentido de Tempo",
    maxRank: 1,
    tip: "Sentido de Tempo (1 graduação): Sabe sempre que horas são, funciona como um cronômetro.",
  },
  {
    id: "ultra-audicao",
    label: "Ultra-Audição",
    maxRank: 1,
    tip: "Ultra-Audição (1 graduação): Ouve sons de frequência muito alta ou baixa (ex: apitos para cães).",
  },
  {
    id: "ultravisao",
    label: "Ultravisão",
    maxRank: 1,
    tip: "Ultravisão (1 graduação): Enxerga luz ultravioleta, permitindo ver normalmente à noite com luz das estrelas/UV.",
  },
  {
    id: "microscopica",
    label: "Visão Microscópica",
    maxRank: 4,
    tip: "Visão Microscópica (1: Poeira; 2: Células; 3: DNA; 4: Átomos): Enxerga coisas extremamente pequenas.",
  },
  {
    id: "penumbra",
    label: "Visão na Penumbra",
    maxRank: 1,
    tip: "Visão na Penumbra (1 graduação): Ignora penalidades por baixa luminosidade (não escuridão total).",
  },
  {
    id: "escuro",
    label: "Visão no Escuro",
    maxRank: 2,
    tip: "Visão no Escuro (2 graduações): Enxerga na escuridão total como se fosse dia normal.",
  },
];
